# Generated by Django 4.2.4 on 2023-10-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=60)),
                ('sclass', models.IntegerField()),
                ('sadr', models.CharField(max_length=60)),
                ('college', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=60)),
                ('sclass', models.IntegerField()),
                ('sadr', models.CharField(max_length=60)),
                ('degree', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=60)),
                ('sclass', models.IntegerField()),
                ('sadr', models.CharField(max_length=60)),
                ('scl', models.CharField(max_length=30)),
            ],
        ),
    ]
