# Generated by Django 4.2.4 on 2023-10-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='sclass',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='degree',
            name='sclass',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='sclass',
            field=models.CharField(max_length=5),
        ),
    ]
